### PR TITLE
Lambda size issues , fix added to readme

### PR DESCRIPTION
**Pull request by taragurung**
Had a zip size issue when deploying the app. Added the fix

### CODE REVIEW

**Comment by iandees** [comment]
Is there a reason why we wouldn't add this to the serverless.yaml that's in the repo?

**Comment by taragurung** [comment]
I thought of just putting it as information to README.MD but Yes, why not add to the serverless.yml as well. I have modified serverless.yml as well.

**Comment by taragurung** [comment]
But I believe it would be nice to have that added to **serverless.yaml**

**Comment by iandees** [comment]
Thanks!

**Pull request merged**
